export const DELETE_BEEHIVE = "DELETE_BEEHIVE";
export const GET_ALL_BEEHIVES = "GET_ALL_BEEHIVES";
export const SAVE_BEEHIVE = "SAVE_BEEHIVE";
export const DELETE_APIARY_SITE = "DELETE_APIARY_SITE";
export const GET_ALL_APIARY_SITES = "GET_ALL_APIARY_SITES";
export const SAVE_APIARY_SITE = "SAVE_APIARY_SITE";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

export const SAVE_TASK = "SAVE_TASK";
export const GET_ALL_TASKS = "GET_ALL_TASKS";
export const POSTPONE_TASK = "POSTPONE_TASK";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const UNCOMPLETED_TASK = "UNCOMPLETED_TASK";
export const DELETE_TASK = "DELETE_TASK";
